# -*- coding: utf-8 -*-
"""projeto-planilhas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKDNMUjllx-5nIO5h9g6KPFEs7JLFPJX
"""

from openpyxl import load_workbook
import random

def copiar_formatacao(origem,destino):
  destino.font = origem.fonte
  destino.fill = origem.fill
  destino.border = origem.border
  destino.number_format = origem.number_format
  destino.protection = origem.protection
  destino.alignment = origem.alignment

arquivo_nce = load_workbook("ORÇAMENTO NCE.xlsx")
pagina_nce = arquivo_nce["Matriz"]

arquivo_paper = load_workbook("ORÇAMENTO PAPER.xlsx")
pagina_paper = arquivo_paper.active

arquivo_grafite = load_workbook("ORÇAMENTO GRAFITE.xlsx")
pagina_grafite = arquivo_grafite.active

arquivo_controle = load_workbook("controle.xlsx")
pagina_controle = arquivo_controle.active

arquivo_doador = load_workbook("NELSON.xlsx")
pagina_doador = arquivo_doador["Table 10"]

linha_ini_nce = 15
linha_ini_paper = 17
linha_ini_grafite = 12
linha_ini_controle = 3
linha_doadora = 3

precos_randomizados_por_valor = {}


while pagina_doador.cell(row=linha_doadora,column=2).value is not None:
  produto = pagina_doador.cell(row=linha_doadora,column=2).value
  un = pagina_doador.cell(row=linha_doadora,column=6).value
  qt = pagina_doador.cell(row=linha_doadora,column=7).value
  unit_nce = pagina_doador.cell(row=linha_doadora,column=8).value

  if unit_nce in precos_randomizados_por_valor:
    unit_paper,unit_grafite = precos_randomizados_por_valor[unit_nce]
  else:
   unit_paper = unit_nce * (1+ random.uniform(0.15,0.25))
   unit_grafite = unit_nce * (1+ random.uniform(0.15,0.25))
   while abs(unit_paper - unit_grafite)< 0.10:
     unit_grafite = unit_nce * (1+ random.uniform(0.15,0.25))
   precos_randomizados_por_valor[unit_nce] = unit_paper,unit_grafite


  pagina_nce.cell(row=linha_ini_nce,column=2).value = produto
  pagina_nce.cell(row=linha_ini_nce,column=3).value = un
  pagina_nce.cell(row=linha_ini_nce,column=4).value = qt
  pagina_nce.cell(row=linha_ini_nce,column=5).value = unit_nce


  pagina_paper.cell(row=linha_ini_paper,column=2).value = produto
  pagina_paper.cell(row=linha_ini_paper,column=3).value = un
  pagina_paper.cell(row=linha_ini_paper,column=4).value = qt
  pagina_paper.cell(row=linha_ini_paper,column=5).value = round(unit_paper,2)


  pagina_grafite.cell(row=linha_ini_grafite,column=2).value = produto
  pagina_grafite.cell(row=linha_ini_grafite,column=3).value = un
  pagina_grafite.cell(row=linha_ini_grafite,column=4).value = qt
  pagina_grafite.cell(row=linha_ini_grafite,column=5).value = round(unit_grafite,2)


  pagina_controle.cell(row=linha_ini_controle,column=2).value = produto
  pagina_controle.cell(row=linha_ini_controle,column=3).value = un
  pagina_controle.cell(row=linha_ini_controle,column=4).value = qt
  pagina_controle.cell(row=linha_ini_controle,column=5).value = unit_nce
  pagina_controle.cell(row=linha_ini_controle,column=8).value = round(unit_paper,2)
  pagina_controle.cell(row=linha_ini_controle,column=11).value = round(unit_grafite,2)


  linha_doadora +=1
  linha_ini_grafite +=1
  linha_ini_paper +=1
  linha_ini_nce +=1
  linha_ini_controle +=1

arquivo_nce.save("ORÇAMENTO NF10619 2025-06-04 NCE.xlsx")
arquivo_paper.save("ORÇAMENTO NF10619 2025-06-04 PAPER&CO.xlsx")
arquivo_grafite.save("ORÇAMENTO NF10619 2025-06-04 GRAFITE.xlsx")
arquivo_controle.save("MODELO DOC NF10619.xlsx")